CREATE TABLE `news_story` (
  `story_id`        INT(10)             NOT NULL AUTO_INCREMENT,
  `story_title`     VARCHAR(255)        NOT NULL DEFAULT '',
  `story_subtitle`  VARCHAR(255)        NOT NULL DEFAULT '',
  `story_topic`     INT(10)             NOT NULL DEFAULT '0',
  `story_type`      VARCHAR(25)         NOT NULL DEFAULT '',
  `story_short`     TEXT,
  `story_text`      TEXT,
  `story_words`     VARCHAR(255)        NOT NULL DEFAULT '',
  `story_desc`      VARCHAR(255)        NOT NULL DEFAULT '',
  `story_alias`     VARCHAR(255)        NOT NULL DEFAULT '',
  `story_important` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `story_default`   TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `story_status`    TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `story_slide`     TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `story_marquee`   TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `story_create`    INT(10)             NOT NULL DEFAULT '0',
  `story_update`    INT(10)             NOT NULL DEFAULT '0',
  `story_publish`   INT(10)             NOT NULL DEFAULT '0',
  `story_expire`    INT(10)             NOT NULL DEFAULT '0',
  `story_uid`       INT(10)             NOT NULL DEFAULT '0',
  `story_author`    VARCHAR(255)        NOT NULL DEFAULT '',
  `story_source`    VARCHAR(255)        NOT NULL DEFAULT '',
  `story_hits`      INT(10)             NOT NULL DEFAULT '0',
  `story_img`       VARCHAR(255)        NOT NULL DEFAULT '',
  `story_comments`  INT(10) UNSIGNED    NOT NULL DEFAULT '0',
  `story_file`      TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `story_rating`    DOUBLE(6, 4)        NOT NULL DEFAULT '0',
  `story_votes`     INT(10) UNSIGNED    NOT NULL DEFAULT '0',
  `dohtml`          TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dobr`            TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `doimage`         TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dosmiley`        TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `doxcode`         TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`story_id`),
  UNIQUE KEY `story_alias` (`story_alias`),
  KEY `story_topic` (`story_topic`),
  KEY `story_title` (`story_title`),
  KEY `story_create` (`story_create`),
  KEY `story_publish` (`story_publish`),
  KEY `story_expire` (`story_expire`),
  KEY `story_uid` (`story_uid`),
  KEY `story_type` (`story_type`),
  KEY `select` (`story_topic`, `story_status`, `story_publish`, `story_expire`),
  FULLTEXT KEY `search` (`story_title`, `story_short`, `story_text`, `story_subtitle`)
);


CREATE TABLE `news_topic` (
  `topic_id`           INT(10) UNSIGNED    NOT NULL  AUTO_INCREMENT,
  `topic_pid`          INT(5) UNSIGNED     NOT NULL  DEFAULT '0',
  `topic_title`        VARCHAR(255)        NOT NULL  DEFAULT '',
  `topic_desc`         TEXT,
  `topic_img`          VARCHAR(255)        NOT NULL  DEFAULT '',
  `topic_weight`       INT(5)              NOT NULL  DEFAULT '0',
  `topic_showtype`     TINYINT(4)          NOT NULL  DEFAULT '0',
  `topic_perpage`      TINYINT(4)          NOT NULL  DEFAULT '0',
  `topic_columns`      TINYINT(4)          NOT NULL  DEFAULT '0',
  `topic_submitter`    INT(10)             NOT NULL  DEFAULT '0',
  `topic_date_created` INT(10)             NOT NULL  DEFAULT '0',
  `topic_date_update`  INT(10)             NOT NULL  DEFAULT '0',
  `topic_asmenu`       TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_online`       TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showtopic`    TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showsub`      TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showauthor`   TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showdate`     TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showpdf`      TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showprint`    TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showmail`     TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_shownav`      TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showhits`     TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_showcoms`     TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_alias`        VARCHAR(255)        NOT NULL  DEFAULT '',
  `topic_homepage`     TINYINT(4)          NOT NULL  DEFAULT '0',
  `topic_show`         TINYINT(1) UNSIGNED NOT NULL  DEFAULT '1',
  `topic_style`        VARCHAR(64)         NOT NULL  DEFAULT '',
  PRIMARY KEY (`topic_id`),
  UNIQUE KEY `topic_alias` (`topic_alias`),
  KEY `topic_pid` (`topic_pid`),
  KEY `topic_online` (`topic_online`),
  KEY `topic_homepage` (`topic_homepage`)
);

CREATE TABLE `news_file` (
  `file_id`       INT(10) UNSIGNED    NOT NULL  AUTO_INCREMENT,
  `file_title`    VARCHAR(255)        NOT NULL  DEFAULT '',
  `file_name`     VARCHAR(255)        NOT NULL  DEFAULT '',
  `file_story`    INT(10)             NOT NULL  DEFAULT '0',
  `file_date`     INT(10)             NOT NULL  DEFAULT '0',
  `file_type`     VARCHAR(64)         NOT NULL  DEFAULT '',
  `file_mimetype` VARCHAR(64)         NOT NULL  DEFAULT '',
  `file_status`   TINYINT(1) UNSIGNED NOT NULL  DEFAULT '0',
  `file_hits`     INT(10)             NOT NULL  DEFAULT '0',
  PRIMARY KEY (`file_id`),
  KEY `file_story` (`file_story`),
  KEY `file_status` (`file_status`),
  KEY `file_date` (`file_date`)
);

CREATE TABLE `news_rate` (
  `rate_id`       INT(10) UNSIGNED    NOT NULL AUTO_INCREMENT,
  `rate_story`    INT(8) UNSIGNED     NOT NULL DEFAULT '0',
  `rate_user`     INT(10)             NOT NULL DEFAULT '0',
  `rate_rating`   TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `rate_hostname` VARCHAR(60)         NOT NULL DEFAULT '',
  `rate_created`  INT(10)             NOT NULL DEFAULT '0',
  PRIMARY KEY (`rate_id`),
  KEY `rate_user` (`rate_user`),
  KEY `rate_hostname` (`rate_hostname`),
  KEY `rate_story` (`rate_story`)
);